name: "ALPR Watched Plates Manager"
version: "1.1"
slug: "codeproject_ai_watchedplates"
description: "Manage watched license plates for CodeProject AI ALPR integration."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
ports:
  8080/tcp: 8080